export const ASSETS = {
  characters: {
    bonk: "/assets/characters/bonk.svg",
    byte: "/assets/characters/byte.svg",
    tank: "/assets/characters/tank.svg",
    nova: "/assets/v2/characters/nova.svg",
    hex: "/assets/v2/characters/hex.svg",
    rift: "/assets/v3/characters/rift.svg",
    fuse: "/assets/v3/characters/fuse.svg",
    lux: "/assets/v3/characters/lux.svg",
  },
  models: {
    tank: "/assets/characters/tank-v2.glb",
  },
  portraits: {
    bonk: "/assets/characters/bonk.svg",
    byte: "/assets/characters/byte.svg",
    tank: "/assets/characters/tank.svg",
    nova: "/assets/v2/characters/nova.svg",
    hex: "/assets/v2/characters/hex.svg",
    rift: "/assets/v3/characters/rift.svg",
    fuse: "/assets/v3/characters/fuse.svg",
    lux: "/assets/v3/characters/lux.svg",
  },
  enemies: {
    slime: "/assets/enemies/slime.svg",
    runner: "/assets/enemies/runner.svg",
    brute: "/assets/enemies/brute.svg",
    shooter: "/assets/enemies/shooter.svg",
    bonklord: "/assets/enemies/bonklord.svg",
    cindermaw: "/assets/enemies/cindermaw.webp",
    stormcoil: "/assets/enemies/stormcoil.webp",
    venomatrix: "/assets/enemies/venomatrix.webp",
    cryovex: "/assets/enemies/cryovex.webp",
  },
  weapons: {
    hammer: "/assets/weapons/hammer.svg",
    energyOrb: "/assets/weapons/energy-orb.svg",
    axe: "/assets/weapons/axe.svg",
    novaBurst: "/assets/v2/weapons/nova-burst.svg",
    hexChain: "/assets/v2/weapons/hex-chain.svg",
    riftDisc: "/assets/v3/weapons/rift-disc.svg",
    pulseMine: "/assets/v3/weapons/pulse-mine.svg",
    lightLance: "/assets/v3/weapons/light-lance.svg",
  },
  upgrades: {
    damage: "/assets/upgrades/damage.svg",
    haste: "/assets/upgrades/haste.svg",
    speed: "/assets/upgrades/speed.svg",
    vitality: "/assets/upgrades/vitality.svg",
    armor: "/assets/upgrades/armor.svg",
    magnet: "/assets/upgrades/magnet.svg",
    critical: "/assets/upgrades/critical.svg",
    multishot: "/assets/upgrades/multishot.svg",
    regeneration: "/assets/v3/upgrades/regeneration.svg",
    barrier: "/assets/v3/upgrades/barrier-matrix.svg",
    area: "/assets/v3/upgrades/area-amplifier.svg",
    recovery: "/assets/v3/upgrades/field-medic.svg",
    boss_hunter: "/assets/v3/upgrades/boss-hunter.svg",
    executioner: "/assets/v3/upgrades/execution-protocol.svg",
    precision: "/assets/v3/upgrades/critical-power.svg",
    fortune: "/assets/v3/upgrades/fortune.svg",
  },
  pickups: {
    xpGem: "/assets/pickups/xp-gem.svg",
  },
  items: {
    medkitEmergency: "/assets/v2/items/medkit-emergency.webp",
    medkitCase: "/assets/v2/items/medkit-case.webp",
    shieldPotion: "/assets/v2/items/shield-potion.webp",
    shieldBattery: "/assets/v2/items/shield-battery.webp",
    overclockCore: "/assets/v2/items/overclock-core.webp",
    teslaCell: "/assets/v2/items/tesla-cell.webp",
    toxicRelic: "/assets/v2/items/toxic-relic.webp",
    phoenixFragment: "/assets/v2/items/phoenix-fragment.webp",
    aegisCapacitor: "/assets/v3/relics/aegis-capacitor.svg",
    apexLens: "/assets/v3/relics/apex-lens.svg",
    echoPrism: "/assets/v3/relics/echo-prism.svg",
    gravitySeed: "/assets/v3/relics/gravity-seed.svg",
  },
  secretPassives: {
    storm_engine: "/assets/v3/secret-passives/storm-engine.svg",
    venom_singularity: "/assets/v3/secret-passives/venom-singularity.svg",
    radiant_bastion: "/assets/v3/secret-passives/radiant-bastion.svg",
    apex_echo: "/assets/v3/secret-passives/apex-echo.svg",
  },
  arenaV2: {
    warningRingDecal: "/assets/arena-v2/warning-ring-decal.webp",
    laneConnectorDecal: "/assets/arena-v2/lane-connector-decal.webp",
  },
  ui: {
    logo: "/assets/ui/bonkageddon-logo.svg",
    relicVaultBanner: "/assets/v3/ui/relic-vault-banner.svg",
  },
} as const;
